const admin = require('firebase-admin');
const serviceAccount = require('./serviceAccountKey.json');

// Firebase Admin'i başlat
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

// Yüklenecek kelime listesi
const words = [
    { targetWord: "PİYANO", forbiddenWords: ["Müzik", "Enstrüman", "Tuş", "Kuyruklu", "Çalmak"] },
    { targetWord: "ASTRONOT", forbiddenWords: ["Uzay", "Roket", "Ay", "Yıldız", "Kıyafet"] },
    { targetWord: "KAMPÜS", forbiddenWords: ["Üniversite", "Öğrenci", "Okul", "Bahçe", "Eğitim"] },

    { targetWord: "DOKTOR", forbiddenWords: ["Hastane", "Muayene", "İlaç", "Hemşire", "Hasta"] },
    { targetWord: "KİTAP", forbiddenWords: ["Okumak", "Sayfa", "Yazar", "Roman", "Kütüphane"] },
    { targetWord: "ARABA", forbiddenWords: ["Tekerlek", "Motor", "Sürücü", "Yakıt", "Direksiyon"] },
    { targetWord: "UÇAK", forbiddenWords: ["Havaalanı", "Pilot", "Kanat", "Uçmak", "Yolcu"] },
    { targetWord: "TELEFON", forbiddenWords: ["Aramak", "Mesaj", "Ekran", "Şarj", "Numara"] },
    { targetWord: "BİLGİSAYAR", forbiddenWords: ["Klavye", "Mouse", "Ekran", "İnternet", "Program"] },
    { targetWord: "ÖĞRETMEN", forbiddenWords: ["Okul", "Ders", "Öğrenci", "Sınıf", "Tahta"] },
    { targetWord: "FUTBOL", forbiddenWords: ["Top", "Gol", "Saha", "Hakem", "Maç"] },
    { targetWord: "DENİZ", forbiddenWords: ["Su", "Dalga", "Kum", "Plaj", "Yüzmek"] },
    { targetWord: "DAĞ", forbiddenWords: ["Tırmanmak", "Zirve", "Yüksek", "Kar", "Doğa"] },

    { targetWord: "KEDİ", forbiddenWords: ["Miyav", "Evcil", "Tüy", "Köpek", "Fare"] },
    { targetWord: "KÖPEK", forbiddenWords: ["Havlamak", "Tasmak", "Evcil", "Kedi", "Sadık"] },
    { targetWord: "SAAT", forbiddenWords: ["Zaman", "Dakika", "Saniye", "Kol", "Alarm"] },
    { targetWord: "GÜNEŞ", forbiddenWords: ["Işık", "Sıcak", "Gündüz", "Gökyüzü", "Yaz"] },
    { targetWord: "AY", forbiddenWords: ["Gece", "Yıldız", "Gökyüzü", "Dolunay", "Uzay"] },
    { targetWord: "YILDIZ", forbiddenWords: ["Gökyüzü", "Gece", "Parlak", "Uzay", "Ay"] },
    { targetWord: "ÇİKOLATA", forbiddenWords: ["Tatlı", "Şeker", "Kakao", "Pasta", "Yemek"] },
    { targetWord: "PASTA", forbiddenWords: ["Doğum günü", "Tatlı", "Mum", "Dilim", "Krema"] },
    { targetWord: "KAHVE", forbiddenWords: ["İçmek", "Fincan", "Kafe", "Türk", "Sıcak"] },
    { targetWord: "ÇAY", forbiddenWords: ["Demlik", "Bardak", "Şeker", "Sıcak", "İçmek"] },

    { targetWord: "HASTANE", forbiddenWords: ["Doktor", "Hasta", "Acil", "Hemşire", "Tedavi"] },
    { targetWord: "POLİS", forbiddenWords: ["Suç", "Hırsız", "Ceza", "Karışmak", "Devriye"] },
    { targetWord: "ASKER", forbiddenWords: ["Ordu", "Silah", "Vatan", "Komutan", "Kışla"] },
    { targetWord: "BANKA", forbiddenWords: ["Para", "Kredi", "Kart", "Faiz", "ATM"] },
    { targetWord: "OKYANUS", forbiddenWords: ["Su", "Büyük", "Deniz", "Balina", "Dalga"] },
    { targetWord: "ORMAN", forbiddenWords: ["Ağaç", "Yeşil", "Doğa", "Hayvan", "Yürümek"] },
    { targetWord: "KAR", forbiddenWords: ["Kış", "Soğuk", "Beyaz", "Yağmak", "Buz"] },
    { targetWord: "YAĞMUR", forbiddenWords: ["Şemsiye", "Islanmak", "Bulut", "Su", "Gökyüzü"] },
    { targetWord: "RÜZGAR", forbiddenWords: ["Esinti", "Hava", "Fırtına", "Soğuk", "Uçurtma"] },
    { targetWord: "ATEŞ", forbiddenWords: ["Yanmak", "Sıcak", "Duman", "Odun", "Alev"] },

    { targetWord: "MASA", forbiddenWords: ["Sandalye", "Yemek", "Ahşap", "Üst", "Oda"] },
    { targetWord: "SANDALYE", forbiddenWords: ["Oturmak", "Masa", "Ayak", "Ahşap", "Ev"] },
    { targetWord: "KAPI", forbiddenWords: ["Anahtar", "Ev", "Açmak", "Kapamak", "Giriş"] },
    { targetWord: "PENCERE", forbiddenWords: ["Cam", "Ev", "Manzara", "Perde", "Açmak"] },
    { targetWord: "TELEVİZYON", forbiddenWords: ["Kanal", "Film", "Dizi", "Kumanda", "Ekran"] },
    { targetWord: "SİNEMA", forbiddenWords: ["Film", "Salon", "Bilet", "Patlamış mısır", "Perde"] },
    { targetWord: "MÜZE", forbiddenWords: ["Tarih", "Eser", "Sergi", "Sanat", "Ziyaret"] },
    { targetWord: "TREN", forbiddenWords: ["Ray", "Vagon", "Gar", "Yolculuk", "Lokomotif"] },
    { targetWord: "OTOBÜS", forbiddenWords: ["Durak", "Şoför", "Yolcu", "Bilet", "Toplu taşıma"] },
    { targetWord: "BİSİKLET", forbiddenWords: ["Pedal", "Tekerlek", "Sürmek", "Kask", "Zincir"] },

    { targetWord: "ELMA", forbiddenWords: ["Meyve", "Kırmızı", "Ağaç", "Yeşil", "Isırmak"] },
    { targetWord: "PORTAKAL", forbiddenWords: ["Meyve", "Turuncu", "Vitamin", "Kabuk", "Sıkmak"] },
    { targetWord: "KARPUZ", forbiddenWords: ["Yaz", "Kırmızı", "Çekirdek", "Dilim", "Serin"] },
    { targetWord: "PATATES", forbiddenWords: ["Kızartma", "Sebze", "Yemek", "Püre", "Toprak"] },
    { targetWord: "DOMATES", forbiddenWords: ["Salata", "Kırmızı", "Sebze", "Sos", "Bahçe"] },
    { targetWord: "PEYNİR", forbiddenWords: ["Kahvaltı", "Süt", "Beyaz", "Kaşar", "Tuzlu"] },
    { targetWord: "EKMEK", forbiddenWords: ["Fırın", "Hamur", "Buğday", "Dilmek", "Yemek"] },
    { targetWord: "SU", forbiddenWords: ["İçmek", "Şeffaf", "Hayat", "Musluk", "Susuzluk"] },
    { targetWord: "ŞEKER", forbiddenWords: ["Tatlı", "Çay", "Beyaz", "Şekerleme", "Tat"] },
    { targetWord: "TUZ", forbiddenWords: ["Yemek", "Tuzluk", "Tat", "Beyaz", "Mutfak"] },

    { targetWord: "BEBEK", forbiddenWords: ["Anne", "Baba", "Küçük", "Ağlamak", "Oyuncak"] },
    { targetWord: "EVLİLİK", forbiddenWords: ["Düğün", "Yüzük", "Nikah", "Eş", "Aşk"] },
    { targetWord: "ARKADAŞ", forbiddenWords: ["Dost", "Sohbet", "Güven", "Birlikte", "Okul"] },
    { targetWord: "AŞK", forbiddenWords: ["Kalp", "Sevgi", "Romantik", "Sevgili", "Duygu"] },
    { targetWord: "MUTLULUK", forbiddenWords: ["Gülmek", "Sevinç", "Pozitif", "Huzur", "Neşe"] },
    { targetWord: "ÜZÜNTÜ", forbiddenWords: ["Ağlamak", "Keder", "Gözyaşı", "Hüzün", "Duygu"] },
    { targetWord: "KORKU", forbiddenWords: ["Karanlık", "Film", "Bağırmak", "Heyecan", "Tehlike"] },
    { targetWord: "RÜYA", forbiddenWords: ["Uyku", "Gece", "Görmek", "Hayal", "Bilinç"] },
    { targetWord: "HAYAL", forbiddenWords: ["Düş", "Kurmak", "Gerçek", "İstemek", "Rüya"] },
    { targetWord: "OYUN", forbiddenWords: ["Eğlence", "Çocuk", "Kazanmak", "Kaybetmek", "Kurallar"] },

    { targetWord: "KALEM", forbiddenWords: ["Yazmak", "Defter", "Mürekkep", "Kurşun", "Silgi"] },
    { targetWord: "DEFTER", forbiddenWords: ["Sayfa", "Okul", "Yazmak", "Kağıt", "Ders"] },
    { targetWord: "ÇANTA", forbiddenWords: ["Okul", "Taşımak", "Eşya", "Sırt", "Fermuar"] },
    { targetWord: "AYAKKABI", forbiddenWords: ["Giymek", "Bağcık", "Yürümek", "Taban", "Spor"] },
    { targetWord: "ŞAPKA", forbiddenWords: ["Baş", "Güneş", "Takmak", "Kep", "Moda"] },
    { targetWord: "GÖZLÜK", forbiddenWords: ["Cam", "Göz", "Takmak", "Numara", "Görmek"] },
    { targetWord: "AİNA", forbiddenWords: ["Yansıma", "Cam", "Bakmak", "Görmek", "Duvar"] },
    { targetWord: "KUAFÖR", forbiddenWords: ["Saç", "Kesmek", "Fön", "Berber", "Tarz"] },
    { targetWord: "HEDİYE", forbiddenWords: ["Doğum günü", "Paket", "Sürpriz", "Mutlu", "Vermek"] },
    { targetWord: "SÜRPRİZ", forbiddenWords: ["Beklenmedik", "Şaşırmak", "Hediye", "Gizli", "Plan"] },

    { targetWord: "ZİNCİR", forbiddenWords: ["Halka", "Demir", "Bağlamak", "Kilit", "Bisiklet"] },
    { targetWord: "BALON", forbiddenWords: ["Şişirmek", "Helyum", "Renkli", "Parti", "Uçmak"] },
    { targetWord: "ŞEMSİYE", forbiddenWords: ["Yağmur", "Islanmak", "Açmak", "Kapanmak", "Korunmak"] },
    { targetWord: "HARİTA", forbiddenWords: ["Yol", "Ülke", "Şehir", "Yön", "Bulmak"] },
    { targetWord: "PUSULA", forbiddenWords: ["Kuzey", "Yön", "Harita", "Keşif", "İğne"] },
    { targetWord: "ADALET", forbiddenWords: ["Mahkeme", "Hakim", "Hukuk", "Suç", "Ceza"] },
    { targetWord: "ZAMAN", forbiddenWords: ["Saat", "Dakika", "Geçmek", "Takvim", "An"] },
    { targetWord: "TAKVİM", forbiddenWords: ["Gün", "Ay", "Yıl", "Tarih", "Duvar"] },
    { targetWord: "KÖPRÜ", forbiddenWords: ["Nehir", "Geçmek", "Bağlamak", "Yol", "Asma"] },
    { targetWord: "MİKROFON", forbiddenWords: ["Ses", "Şarkı", "Konuşmak", "Sahne", "Hoparlör"] },

    { targetWord: "ROBOT", forbiddenWords: ["Yapay", "Makine", "Teknoloji", "Otomatik", "Metal"] },
    { targetWord: "YAZILIM", forbiddenWords: ["Kod", "Program", "Bilgisayar", "Geliştirici", "Uygulama"] },
    { targetWord: "İNTERNET", forbiddenWords: ["Web", "Bağlantı", "Site", "Online", "Modem"] },
    { targetWord: "KAMERA", forbiddenWords: ["Fotoğraf", "Video", "Çekmek", "Lens", "Kaydetmek"] },
    { targetWord: "FOTOĞRAF", forbiddenWords: ["Resim", "Çekmek", "Makine", "Poz", "Hatıra"] },
    { targetWord: "TATİL", forbiddenWords: ["Yaz", "Deniz", "Otel", "Dinlenmek", "Gezi"] },
    { targetWord: "VALİZ", forbiddenWords: ["Seyahat", "Kıyafet", "Toplamak", "Tekerlek", "Taşımak"] },
    { targetWord: "PASAPORT", forbiddenWords: ["Yurt dışı", "Kimlik", "Havalimanı", "Vize", "Ülke"] },
    { targetWord: "UZAY", forbiddenWords: ["Gezegen", "Yıldız", "Astronot", "Roket", "Boşluk"] },
    { targetWord: "ROKET", forbiddenWords: ["Uzay", "Fırlatmak", "Astronot", "Hız", "NASA"] },

    { targetWord: "AMPUL", forbiddenWords: ["Işık", "Elektrik", "Lamba", "Aydınlatmak", "Tavan"] },
    { targetWord: "ASANSÖR", forbiddenWords: ["Kat", "Yukarı", "Aşağı", "Düğme", "Bina"] },
    { targetWord: "BALKON", forbiddenWords: ["Ev", "Manzara", "Dışarı", "Korkuluk", "Çiçek"] },
    { targetWord: "BARDAK", forbiddenWords: ["Su", "İçmek", "Cam", "Mutfak", "Kırılmak"] },
    { targetWord: "BATARYA", forbiddenWords: ["Pil", "Enerji", "Şarj", "Elektrik", "Güç"] },
    { targetWord: "BATTANİYE", forbiddenWords: ["Soğuk", "Yatak", "Örtmek", "Kış", "Sıcak"] },
    { targetWord: "BİLET", forbiddenWords: ["Giriş", "Sinema", "Maç", "Numara", "Satın almak"] },
    { targetWord: "BULAŞIK", forbiddenWords: ["Tabak", "Yıkamak", "Mutfak", "Sabun", "Lavabo"] },
    { targetWord: "ÇEKMECE", forbiddenWords: ["Dolap", "Açmak", "Kapatmak", "Kıyafet", "Mobilya"] },
    { targetWord: "ÇİVİ", forbiddenWords: ["Çekiç", "Duvar", "Demir", "Çakmak", "Tahta"] },

    { targetWord: "DALGIÇ", forbiddenWords: ["Deniz", "Tüp", "Su", "Yüzmek", "Maske"] },
    { targetWord: "DİŞÇİ", forbiddenWords: ["Diş", "Ağrı", "Muayene", "Dolgu", "Klinik"] },
    { targetWord: "DUDAK", forbiddenWords: ["Ağız", "Öpmek", "Yüz", "Konuşmak", "Ruj"] },
    { targetWord: "DÜRBÜN", forbiddenWords: ["Bakmak", "Uzak", "Göz", "Büyütmek", "Manzara"] },
    { targetWord: "EKRAN", forbiddenWords: ["Televizyon", "Telefon", "Görüntü", "Cam", "İzlemek"] },
    { targetWord: "FIRÇA", forbiddenWords: ["Saç", "Boyamak", "Diş", "Temizlik", "Tarama"] },
    { targetWord: "FİDAN", forbiddenWords: ["Ağaç", "Toprak", "Dikmek", "Bahçe", "Yeşil"] },
    { targetWord: "FİYAT", forbiddenWords: ["Para", "Etiket", "Ucuz", "Pahalı", "Satın almak"] },
    { targetWord: "GARAJ", forbiddenWords: ["Araba", "Park", "Kapı", "Ev", "Depo"] },
    { targetWord: "GAZETE", forbiddenWords: ["Haber", "Okumak", "Manşet", "Kağıt", "Basın"] },

    { targetWord: "GÖMLEK", forbiddenWords: ["Kıyafet", "Giymek", "Düğme", "Yaka", "Pantolon"] },
    { targetWord: "GÜVERCİN", forbiddenWords: ["Kuş", "Kanat", "Uçmak", "Beyaz", "Şehir"] },
    { targetWord: "HAMAK", forbiddenWords: ["Yatmak", "Ağaç", "Dinlenmek", "Bahçe", "Salınmak"] },
    { targetWord: "HAVLU", forbiddenWords: ["Kurulamak", "Banyo", "Su", "Bez", "Islak"] },
    { targetWord: "HELMET", forbiddenWords: ["Kask", "Koruma", "Motor", "Baş", "Sürmek"] },
    { targetWord: "ISLIK", forbiddenWords: ["Ses", "Ağız", "Çalmak", "Hava", "Dikkat"] },
    { targetWord: "İP", forbiddenWords: ["Bağlamak", "Halat", "Düğüm", "Çekmek", "Uzun"] },
    { targetWord: "JİLET", forbiddenWords: ["Kesmek", "Tıraş", "Bıçak", "Sakız", "Keskin"] },
    { targetWord: "KAMP", forbiddenWords: ["Çadır", "Doğa", "Ateş", "Gece", "Orman"] },
    { targetWord: "KANAT", forbiddenWords: ["Uçmak", "Kuş", "Uçak", "Tüy", "Gökyüzü"] },

    { targetWord: "KAPLAN", forbiddenWords: ["Hayvan", "Orman", "Çizgili", "Vahşi", "Aslan"] },
    { targetWord: "KAVANOZ", forbiddenWords: ["Cam", "Kapak", "Reçel", "Mutfak", "Saklamak"] },
    { targetWord: "KEMER", forbiddenWords: ["Pantolon", "Bel", "Takmak", "Deri", "Delik"] },
    { targetWord: "KIRBAÇ", forbiddenWords: ["At", "Vurmak", "Deri", "Ceza", "Hayvan"] },
    { targetWord: "KİLİT", forbiddenWords: ["Anahtar", "Kapı", "Açmak", "Kapatmak", "Güvenlik"] },
    { targetWord: "KOKU", forbiddenWords: ["Burun", "Parfüm", "His", "Güzel", "Kötü"] },
    { targetWord: "KULE", forbiddenWords: ["Yüksek", "Bina", "Tarihi", "Şehir", "Zirve"] },
    { targetWord: "KUMBARA", forbiddenWords: ["Para", "Biriktirmek", "Bozuk", "Çocuk", "Tasarruf"] },
    { targetWord: "LİMON", forbiddenWords: ["Ekşi", "Sarı", "Meyve", "Sıkmak", "Çay"] },
    { targetWord: "LOKMA", forbiddenWords: ["Tatlı", "Şerbet", "Yemek", "Hamur", "Kızartma"] },

    { targetWord: "MADALYA", forbiddenWords: ["Ödül", "Altın", "Spor", "Başarı", "Yarış"] },
    { targetWord: "MAKAS", forbiddenWords: ["Kesmek", "Kağıt", "Saç", "Bıçak", "Alet"] },
    { targetWord: "MANZARA", forbiddenWords: ["Görmek", "Doğa", "Güzel", "Dağ", "Deniz"] },
    { targetWord: "MASKE", forbiddenWords: ["Yüz", "Koruma", "Pandemi", "Takmak", "Gizlemek"] },
    { targetWord: "MAYMUN", forbiddenWords: ["Hayvan", "Ağaç", "Muz", "Orman", "Zıplamak"] },
    { targetWord: "MERDİVEN", forbiddenWords: ["Basamak", "Yukarı", "Aşağı", "Bina", "Çıkmak"] },
    { targetWord: "MEŞALE", forbiddenWords: ["Ateş", "Işık", "Olimpiyat", "Yanmak", "Taşımak"] },
    { targetWord: "MIZRAK", forbiddenWords: ["Silah", "Atmak", "Savaş", "Keskin", "Av"] },
    { targetWord: "MOTOR", forbiddenWords: ["Araba", "Makine", "Çalışmak", "Yakıt", "Güç"] },
    { targetWord: "MUM", forbiddenWords: ["Işık", "Yanmak", "Doğum günü", "Alev", "Erimek"] },

    { targetWord: "NAR", forbiddenWords: ["Meyve", "Kırmızı", "Tane", "Kabuk", "Ekşi"] },
    { targetWord: "NEHİR", forbiddenWords: ["Su", "Akmak", "Köprü", "Deniz", "Uzun"] },
    { targetWord: "OK", forbiddenWords: ["Yay", "Atmak", "Hedef", "Silah", "Savaş"] },
    { targetWord: "OTEL", forbiddenWords: ["Tatil", "Oda", "Kalmak", "Resepsiyon", "Yatak"] },
    { targetWord: "PANO", forbiddenWords: ["Duyuru", "Duvar", "Asmak", "Kağıt", "Bilgi"] },
    { targetWord: "PARK", forbiddenWords: ["Çocuk", "Salıncak", "Yeşil", "Oturmak", "Bank"] },
    { targetWord: "PERDE", forbiddenWords: ["Pencere", "Tiyatro", "Kapatmak", "Açmak", "Kumaş"] },
    { targetWord: "PİKNİK", forbiddenWords: ["Sepet", "Doğa", "Yemek", "Aile", "Çimen"] },
    { targetWord: "PİLOT", forbiddenWords: ["Uçak", "Kokpit", "Hava", "Uçmak", "Kaptan"] },
    { targetWord: "PİRAMİT", forbiddenWords: ["Mısır", "Üçgen", "Tarihi", "Antik", "Firavun"] },

    { targetWord: "RADYO", forbiddenWords: ["Müzik", "Dinlemek", "Frekans", "Yayın", "Ses"] },
    { targetWord: "RAY", forbiddenWords: ["Tren", "Demir", "Yol", "Vagon", "Hat"] },
    { targetWord: "REÇEL", forbiddenWords: ["Kahvaltı", "Tatlı", "Meyve", "Şeker", "Kavanoz"] },
    { targetWord: "RÜZGARLIK", forbiddenWords: ["Mont", "Soğuk", "Ceket", "Kıyafet", "Koruma"] },
    { targetWord: "SAHNE", forbiddenWords: ["Tiyatro", "Müzik", "Gösteri", "Perde", "Sanatçı"] },
    { targetWord: "SALINCAK", forbiddenWords: ["Park", "Çocuk", "Oturmak", "İp", "Bahçe"] },
    { targetWord: "SANDIK", forbiddenWords: ["Kutu", "Tahta", "Saklamak", "Kapak", "Depo"] },
    { targetWord: "SERÇE", forbiddenWords: ["Kuş", "Küçük", "Kanat", "Uçmak", "Ağaç"] },
    { targetWord: "SİNEK", forbiddenWords: ["Uçmak", "Yaz", "Isırmak", "Böcek", "Rahatsız"] },
    { targetWord: "SİNYAL", forbiddenWords: ["Işık", "Telefon", "Bağlantı", "Uyarı", "Ses"] },

    { targetWord: "ŞAMPİYON", forbiddenWords: ["Birinci", "Kupa", "Yarış", "Kazanan", "Spor"] },
    { targetWord: "ŞARJ", forbiddenWords: ["Telefon", "Pil", "Enerji", "Kablo", "Elektrik"] },
    { targetWord: "ŞEHİR", forbiddenWords: ["Kalabalık", "Bina", "Yol", "Merkez", "İl"] },
    { targetWord: "ŞOFÖR", forbiddenWords: ["Araba", "Sürmek", "Ehliyet", "Direksiyon", "Yol"] },
    { targetWord: "TABLO", forbiddenWords: ["Resim", "Duvar", "Sanat", "Çerçeve", "Boyama"] },
    { targetWord: "TARLA", forbiddenWords: ["Çiftçi", "Ekmek", "Toprak", "Hasat", "Buğday"] },
    { targetWord: "TAVUK", forbiddenWords: ["Yumurta", "Hayvan", "Kümes", "Kanat", "Et"] },
    { targetWord: "TERMOS", forbiddenWords: ["Sıcak", "Soğuk", "İçecek", "Taşımak", "Kap"] },
    { targetWord: "TIRNAK", forbiddenWords: ["El", "Kesmek", "Oje", "Parmak", "Uzamak"] },
    { targetWord: "TORBA", forbiddenWords: ["Poşet", "Taşımak", "Market", "Eşya", "Kumaş"] },

    { targetWord: "TURŞU", forbiddenWords: ["Ekşi", "Sebze", "Kavanoz", "Salatalık", "Yemek"] },
    { targetWord: "UYDU", forbiddenWords: ["Uzay", "Dünya", "Yörünge", "Sinyal", "Roket"] },
    { targetWord: "ÜTÜ", forbiddenWords: ["Kıyafet", "Kırışık", "Buhar", "Isı", "Düzeltmek"] },
    { targetWord: "VİTRİN", forbiddenWords: ["Mağaza", "Cam", "Ürün", "Göstermek", "Dükkan"] },
    { targetWord: "YAKA", forbiddenWords: ["Gömlek", "Kıyafet", "Boyun", "Düğme", "Takım"] },
    { targetWord: "YASTIK", forbiddenWords: ["Uyku", "Yatak", "Baş", "Yumuşak", "Yorgan"] },
    { targetWord: "YEMİN", forbiddenWords: ["Söz", "Mahkeme", "Doğru", "And", "Ciddi"] },
    { targetWord: "YOLCU", forbiddenWords: ["Otobüs", "Uçak", "Seyahat", "Bilet", "Gitmek"] },
    { targetWord: "ZARF", forbiddenWords: ["Mektup", "Posta", "Kağıt", "Adres", "Pul"] },
    { targetWord: "ZEMİN", forbiddenWords: ["Yer", "Alt", "Parke", "Toprak", "Yürümek"] },

    { targetWord: "ABAJUR", forbiddenWords: ["Lamba", "Işık", "Masa", "Ampul", "Gece"] },
    { targetWord: "AĞAÇ", forbiddenWords: ["Orman", "Yaprak", "Dal", "Odun", "Yeşil"] },
    { targetWord: "AKVARYUM", forbiddenWords: ["Balık", "Su", "Cam", "Yem", "Evcil"] },
    { targetWord: "ALARM", forbiddenWords: ["Saat", "Uyanmak", "Ses", "Çalmak", "Telefon"] },
    { targetWord: "ANAHTARLIK", forbiddenWords: ["Anahtar", "Takmak", "Metal", "Çanta", "Kapı"] },
    { targetWord: "ANTRENÖR", forbiddenWords: ["Spor", "Takım", "Çalıştırmak", "Maç", "Oyuncu"] },
    { targetWord: "ARKEOLOG", forbiddenWords: ["Kazı", "Tarih", "Fosil", "Antik", "Toprak"] },
    { targetWord: "ATLAS", forbiddenWords: ["Harita", "Kitap", "Dünya", "Ülke", "Coğrafya"] },
    { targetWord: "AVİZE", forbiddenWords: ["Tavan", "Işık", "Lamba", "Kristal", "Salon"] },
    { targetWord: "AYÇİÇEĞİ", forbiddenWords: ["Sarı", "Çiçek", "Güneş", "Tarlа", "Tohum"] },

    { targetWord: "BALTA", forbiddenWords: ["Odun", "Kesmek", "Ağaç", "Demir", "Sap"] },
    { targetWord: "BARUT", forbiddenWords: ["Patlama", "Silah", "Ateş", "Toz", "Savaş"] },
    { targetWord: "BAVUL", forbiddenWords: ["Valiz", "Seyahat", "Kıyafet", "Toplamak", "Tatil"] },
    { targetWord: "BESTE", forbiddenWords: ["Müzik", "Şarkı", "Nota", "Yazmak", "Sanat"] },
    { targetWord: "BİBER", forbiddenWords: ["Acı", "Sebze", "Kırmızı", "Yemek", "Baharat"] },
    { targetWord: "BİLGELİK", forbiddenWords: ["Akıl", "Deneyim", "Yaşlı", "Bilgi", "Öğüt"] },
    { targetWord: "BİSİKLETÇİ", forbiddenWords: ["Pedal", "Spor", "Yarış", "Kask", "Tur"] },
    { targetWord: "BODRUM", forbiddenWords: ["Ev", "Alt", "Kiler", "Depo", "Kat"] },
    { targetWord: "BORU", forbiddenWords: ["Su", "Akmak", "Metal", "Tesisat", "Uzun"] },
    { targetWord: "BOZUKLUK", forbiddenWords: ["Arıza", "Çalışmamak", "Tamir", "Makine", "Sorun"] },

    { targetWord: "CAMBAZ", forbiddenWords: ["Sirk", "Denge", "İp", "Gösteri", "Yüksek"] },
    { targetWord: "CEKET", forbiddenWords: ["Mont", "Giymek", "Kıyafet", "Düğme", "Soğuk"] },
    { targetWord: "CETVEL", forbiddenWords: ["Ölçmek", "Çizgi", "Okul", "Santim", "Kağıt"] },
    { targetWord: "CÜZDAN", forbiddenWords: ["Para", "Kart", "Cep", "Kimlik", "Taşımak"] },
    { targetWord: "ÇAĞRI", forbiddenWords: ["Telefon", "Aramak", "Ses", "Davet", "İletişim"] },
    { targetWord: "ÇAPA", forbiddenWords: ["Gemi", "Deniz", "Bağlamak", "Demir", "Liman"] },
    { targetWord: "ÇARŞAF", forbiddenWords: ["Yatak", "Örtmek", "Nevresim", "Beyaz", "Uyku"] },
    { targetWord: "ÇELİK", forbiddenWords: ["Metal", "Demir", "Sağlam", "Endüstri", "Sert"] },
    { targetWord: "ÇORAP", forbiddenWords: ["Ayak", "Giymek", "Ayakkabı", "Çift", "Kıyafet"] },
    { targetWord: "ÇÖL", forbiddenWords: ["Kum", "Sıcak", "Deve", "Kurak", "Afrika"] },

    { targetWord: "DAVUL", forbiddenWords: ["Müzik", "Çalmak", "Baget", "Ritim", "Enstrüman"] },
    { targetWord: "DEDEKTİF", forbiddenWords: ["Suç", "Araştırmak", "Polis", "İpucu", "Gizem"] },
    { targetWord: "DEMLİK", forbiddenWords: ["Çay", "Kaynamak", "Su", "Mutfak", "Demlemek"] },
    { targetWord: "DENGE", forbiddenWords: ["Eşit", "Ağırlık", "Durmak", "Terazi", "Sağlamak"] },
    { targetWord: "DERGİ", forbiddenWords: ["Okumak", "Kapak", "Sayfa", "Haber", "Aylık"] },
    { targetWord: "DİKİŞ", forbiddenWords: ["İğne", "İplik", "Kumaş", "Terzi", "Elbise"] },
    { targetWord: "DİYET", forbiddenWords: ["Kilo", "Zayıflamak", "Yemek", "Sağlık", "Spor"] },
    { targetWord: "DOLAP", forbiddenWords: ["Kıyafet", "Mutfak", "Kapak", "Raf", "Buzdolabı"] },
    { targetWord: "DOMİNO", forbiddenWords: ["Taş", "Oyun", "Dizmek", "Yıkılmak", "Siyah"] },
    { targetWord: "DÜĞÜM", forbiddenWords: ["İp", "Bağlamak", "Çözmek", "Sıkı", "Halat"] },

    { targetWord: "EFSANE", forbiddenWords: ["Hikaye", "Mit", "Kahraman", "Anlatmak", "Eski"] },
    { targetWord: "ELDİVEN", forbiddenWords: ["El", "Soğuk", "Kış", "Takmak", "Çift"] },
    { targetWord: "EMANET", forbiddenWords: ["Güven", "Vermek", "Geçici", "Saklamak", "Sorumluluk"] },
    { targetWord: "ERZAK", forbiddenWords: ["Yiyecek", "Depo", "Kiler", "Gıda", "Saklamak"] },
    { targetWord: "ETİKET", forbiddenWords: ["Fiyat", "Yapıştırmak", "Ürün", "Yazı", "Market"] },
    { targetWord: "FABRİKA", forbiddenWords: ["Üretim", "İşçi", "Sanayi", "Makine", "Baca"] },
    { targetWord: "FENER", forbiddenWords: ["Işık", "Gece", "El", "Pil", "Kamp"] },
    { targetWord: "FERMUAR", forbiddenWords: ["Mont", "Çanta", "Açmak", "Kapatmak", "Kıyafet"] },
    { targetWord: "FISKIYE", forbiddenWords: ["Su", "Bahçe", "Park", "Akmak", "Süs"] },
    { targetWord: "FIRTINA", forbiddenWords: ["Rüzgar", "Yağmur", "Şimşek", "Şiddetli", "Hava"] },

    { targetWord: "GALAKSİ", forbiddenWords: ["Uzay", "Yıldız", "Evren", "Samanyolu", "Gezegen"] },
    { targetWord: "GARSON", forbiddenWords: ["Restoran", "Sipariş", "Masa", "Yemek", "Servis"] },
    { targetWord: "GELENEK", forbiddenWords: ["Kültür", "Eski", "Adet", "Nesil", "Toplum"] },
    { targetWord: "GEMİ", forbiddenWords: ["Deniz", "Kaptan", "Liman", "Yolculuk", "Yük"] },
    { targetWord: "GERGİN", forbiddenWords: ["Stres", "Sinir", "Kaygı", "Tartışma", "Huzursuz"] },
    { targetWord: "GİŞE", forbiddenWords: ["Bilet", "Satmak", "Cam", "Küçük pencere", "Sıra"] },
    { targetWord: "GÖKDELEN", forbiddenWords: ["Yüksek", "Bina", "Şehir", "Kat", "Ofis"] },
    { targetWord: "GÖLGE", forbiddenWords: ["Güneş", "Karanlık", "Işık", "Ağaç", "Serin"] },
    { targetWord: "GÖREV", forbiddenWords: ["Sorumluluk", "İş", "Verilmek", "Tamamlamak", "Memur"] },
    { targetWord: "GREV", forbiddenWords: ["İşçi", "Çalışmamak", "Hak", "Protesto", "Sendika"] },

    { targetWord: "HAFIZA", forbiddenWords: ["Beyin", "Hatırlamak", "Unutmak", "Zihin", "Bilgi"] },
    { targetWord: "HALI", forbiddenWords: ["Zemin", "Ev", "Desen", "Yıkamak", "Salon"] },
    { targetWord: "HAN", forbiddenWords: ["Tarihi", "Konaklama", "Kervan", "Eski", "Yol"] },
    { targetWord: "HARÇLIK", forbiddenWords: ["Para", "Çocuk", "Aile", "Vermek", "Okul"] },
    { targetWord: "HASAT", forbiddenWords: ["Tarla", "Toplamak", "Buğday", "Çiftçi", "Ürün"] },
    { targetWord: "HAYVANAT", forbiddenWords: ["Canlı", "Tür", "Doğa", "Vahşi", "Evcil"] },
    { targetWord: "HİKAYE", forbiddenWords: ["Anlatmak", "Kitap", "Yazar", "Kahraman", "Olay"] },
    { targetWord: "HOROZ", forbiddenWords: ["Tavuk", "Sabah", "Ötmek", "Kümes", "Hayvan"] },
    { targetWord: "HÜCRE", forbiddenWords: ["Biyoloji", "Canlı", "Mikroskop", "Bölünmek", "Çekirdek"] },
    { targetWord: "ISPARTA", forbiddenWords: ["Gül", "Şehir", "Akdeniz", "Türkiye", "Lavanta"] },


    { targetWord: "İMZA", forbiddenWords: ["Atmak", "Belge", "Kalem", "Onay", "İsim"] },
    { targetWord: "İSKELET", forbiddenWords: ["Kemik", "Vücut", "Kafatası", "İnsan", "Anatomi"] },
    { targetWord: "İSTASYON", forbiddenWords: ["Tren", "Durak", "Yolcu", "Ray", "Gar"] },
    { targetWord: "İZCİ", forbiddenWords: ["Kamp", "Doğa", "Üniforma", "Yemin", "Genç"] },
    { targetWord: "JAKUZI", forbiddenWords: ["Su", "Köpük", "Banyo", "Sıcak", "Spa"] },
    { targetWord: "JET", forbiddenWords: ["Uçak", "Hızlı", "Motor", "Hava", "Askeri"] },
    { targetWord: "JÜRİ", forbiddenWords: ["Yarışma", "Karar", "Seçmek", "Üye", "Oylama"] },
    { targetWord: "KABLO", forbiddenWords: ["Elektrik", "Bağlantı", "Tel", "Şarj", "Uzun"] },
    { targetWord: "KADRAJ", forbiddenWords: ["Fotoğraf", "Kamera", "Çekmek", "Görüntü", "Çerçeve"] },
    { targetWord: "KALE", forbiddenWords: ["Tarihi", "Sur", "Savaş", "Taş", "Ortaçağ"] },

    { targetWord: "KALP", forbiddenWords: ["Atmak", "Aşk", "Organ", "Kan", "Duygu"] },
    { targetWord: "KAMPÜS", forbiddenWords: ["Üniversite", "Öğrenci", "Ders", "Bina", "Okul"] },
    { targetWord: "KARAVAN", forbiddenWords: ["Tatil", "Araç", "Yolculuk", "Ev", "Gezmek"] },
    { targetWord: "KARGO", forbiddenWords: ["Paket", "Göndermek", "Teslim", "Şirket", "Kutu"] },
    { targetWord: "KASIRGA", forbiddenWords: ["Fırtına", "Rüzgar", "Şiddetli", "Doğa", "Yıkım"] },
    { targetWord: "KATİL", forbiddenWords: ["Cinayet", "Suç", "Polis", "Hapishane", "Mahkeme"] },
    { targetWord: "KAZAK", forbiddenWords: ["Kış", "Giymek", "Yün", "Soğuk", "Kıyafet"] },
    { targetWord: "KEMAN", forbiddenWords: ["Müzik", "Yay", "Tel", "Enstrüman", "Çalmak"] },
    { targetWord: "KERESTE", forbiddenWords: ["Odun", "Tahta", "İnşaat", "Ağaç", "Kesmek"] },
    { targetWord: "KISMET", forbiddenWords: ["Şans", "Nasip", "Evlilik", "Talih", "Yazgı"] },

    { targetWord: "KİRA", forbiddenWords: ["Ev", "Para", "Aylık", "Ödemek", "Sözleşme"] },
    { targetWord: "KIVILCIM", forbiddenWords: ["Ateş", "Küçük", "Yanmak", "Kıvılmak", "Başlangıç"] },
    { targetWord: "KİMYA", forbiddenWords: ["Deney", "Laboratuvar", "Madde", "Element", "Bilim"] },
    { targetWord: "KONSER", forbiddenWords: ["Müzik", "Sahne", "Sanatçı", "Bilet", "Canlı"] },
    { targetWord: "KORSAN", forbiddenWords: ["Gemi", "Deniz", "Hazine", "Kaptan", "Macera"] },
    { targetWord: "KOZALAK", forbiddenWords: ["Çam", "Ağaç", "Orman", "Tohum", "Kahverengi"] },
    { targetWord: "KREM", forbiddenWords: ["Cilt", "Sürmek", "Nem", "Kutu", "Beyaz"] },
    { targetWord: "KROKİ", forbiddenWords: ["Harita", "Çizim", "Yer", "Adres", "Yol"] },
    { targetWord: "KULAKLIK", forbiddenWords: ["Müzik", "Telefon", "Dinlemek", "Ses", "Takmak"] },
    { targetWord: "KURŞUN", forbiddenWords: ["Mermi", "Metal", "Silah", "Gri", "Ağır"] },

    { targetWord: "KÜREK", forbiddenWords: ["Deniz", "Tekne", "Çekmek", "Su", "Spor"] },
    { targetWord: "LABİRENT", forbiddenWords: ["Yol", "Kaybolmak", "Çıkış", "Bulmaca", "Karışık"] },
    { targetWord: "LEYLEK", forbiddenWords: ["Kuş", "Uzun", "Göç", "Bebek", "Kanat"] },
    { targetWord: "LİDER", forbiddenWords: ["Başkan", "Yönetmek", "Öncü", "Takım", "Grup"] },
    { targetWord: "LOKOMOTİF", forbiddenWords: ["Tren", "Vagon", "Ray", "Çekmek", "Demir"] },
    { targetWord: "MAKİNA", forbiddenWords: ["Çalışmak", "Motor", "Metal", "Üretim", "Alet"] },
    { targetWord: "MANŞET", forbiddenWords: ["Gazete", "Başlık", "Haber", "Büyük", "Yazı"] },
    { targetWord: "MARATON", forbiddenWords: ["Koşu", "Uzun", "Yarış", "Spor", "Kilometre"] },
    { targetWord: "MASAL", forbiddenWords: ["Prens", "Peri", "Çocuk", "Hikaye", "Anlatmak"] },
    { targetWord: "MEKTUP", forbiddenWords: ["Zarf", "Posta", "Yazmak", "Pul", "Adres"] },

    { targetWord: "MERKEZ", forbiddenWords: ["Orta", "Şehir", "Ana", "Toplanmak", "Nokta"] },
    { targetWord: "METRO", forbiddenWords: ["Tren", "Yeraltı", "Durak", "Ulaşım", "Ray"] },
    { targetWord: "MİMAR", forbiddenWords: ["Bina", "Çizim", "Plan", "İnşaat", "Proje"] },
    { targetWord: "MİNARE", forbiddenWords: ["Cami", "Ezan", "Yüksek", "Kubbe", "İslam"] },
    { targetWord: "MİSAFİR", forbiddenWords: ["Ev", "Ziyaret", "Ağırlamak", "Konuk", "Gelmek"] },
    { targetWord: "MİTİNG", forbiddenWords: ["Kalabalık", "Siyaset", "Konuşma", "Alan", "Toplanmak"] },
    { targetWord: "MUTFAK", forbiddenWords: ["Yemek", "Ocak", "Dolap", "Tencere", "Ev"] },
    { targetWord: "NABIZ", forbiddenWords: ["Kalp", "Atmak", "Doktor", "Bilek", "Sağlık"] },
    { targetWord: "NAKIŞ", forbiddenWords: ["İğne", "İplik", "Kumaş", "Süsleme", "Desen"] },
    { targetWord: "NİŞAN", forbiddenWords: ["Yüzük", "Evlilik", "Söz", "Çift", "Tören"] },

    { targetWord: "OBJEKTİF", forbiddenWords: ["Kamera", "Lens", "Fotoğraf", "Yakın", "Uzak"] },
    { targetWord: "ODAK", forbiddenWords: ["Merkez", "Dikkat", "Toplanmak", "Nokta", "Konsantrasyon"] },
    { targetWord: "OPERASYON", forbiddenWords: ["Ameliyat", "Doktor", "Hastane", "Cerrah", "Müdahale"] },
    { targetWord: "OTURUM", forbiddenWords: ["Toplantı", "Meclis", "Konuşma", "Başlamak", "Karar"] },
    { targetWord: "OYMA", forbiddenWords: ["Tahta", "Sanat", "Bıçak", "Şekil", "El işi"] },
    { targetWord: "ÖDÜNÇ", forbiddenWords: ["Almak", "Vermek", "Geçici", "Kitap", "Geri"] },
    { targetWord: "ÖRDEK", forbiddenWords: ["Kuş", "Su", "Gölet", "Sarı", "Vak"] },
    { targetWord: "ÖRÜMCEK", forbiddenWords: ["Ağ", "Böcek", "Sekiz", "Duvar", "Korku"] },
    { targetWord: "ÖZLEM", forbiddenWords: ["Hasret", "Uzak", "Sevgi", "Duygu", "Aramak"] },
    { targetWord: "PANAYIR", forbiddenWords: ["Eğlence", "Lunapark", "Kalabalık", "Oyun", "Alan"] },


    { targetWord: "PANKART", forbiddenWords: ["Yazı", "Protesto", "Taşımak", "Kalabalık", "Slogan"] },
    { targetWord: "PARFÜM", forbiddenWords: ["Koku", "Şişe", "Sıkmak", "Güzel", "Kozmetik"] },
    { targetWord: "PASPAS", forbiddenWords: ["Temizlik", "Yer", "Silmek", "Islak", "Ev"] },
    { targetWord: "PATEN", forbiddenWords: ["Kaymak", "Tekerlek", "Ayak", "Spor", "Denge"] },
    { targetWord: "PATRON", forbiddenWords: ["İş", "Şirket", "Yönetmek", "Müdür", "Çalışan"] },
    { targetWord: "PENGUEN", forbiddenWords: ["Kutup", "Soğuk", "Siyah", "Beyaz", "Kuş"] },
    { targetWord: "PERON", forbiddenWords: ["Tren", "İstasyon", "Ray", "Yolcu", "Beklemek"] },
    { targetWord: "PİL", forbiddenWords: ["Enerji", "Elektrik", "Şarj", "Kumanda", "Batarya"] },
    { targetWord: "PİRİNÇ", forbiddenWords: ["Pilav", "Yemek", "Beyaz", "Tane", "Mutfak"] },
    { targetWord: "PLAK", forbiddenWords: ["Müzik", "Gramofon", "Siyah", "Disk", "Şarkı"] },

    { targetWord: "POSTER", forbiddenWords: ["Duvar", "Resim", "Asmak", "Genç", "Oda"] },
    { targetWord: "PRİZ", forbiddenWords: ["Elektrik", "Fiş", "Duvar", "Kablo", "Takmak"] },
    { targetWord: "PROVA", forbiddenWords: ["Deneme", "Tiyatro", "Hazırlık", "Tekrar", "Sahne"] },
    { targetWord: "RAF", forbiddenWords: ["Dolap", "Kitap", "Duvar", "Yerleştirmek", "Ahşap"] },
    { targetWord: "REHBER", forbiddenWords: ["Tur", "Anlatmak", "Gezi", "Yol göstermek", "Grup"] },
    { targetWord: "RENK", forbiddenWords: ["Boyamak", "Mavi", "Kırmızı", "Sarı", "Görmek"] },
    { targetWord: "RESİM", forbiddenWords: ["Çizmek", "Boyamak", "Kağıt", "Sanat", "Tablo"] },
    { targetWord: "RİTİM", forbiddenWords: ["Müzik", "Tempo", "Davul", "Hız", "Şarkı"] },
    { targetWord: "ROZET", forbiddenWords: ["Takmak", "Yaka", "Sembol", "Metal", "Ödül"] },
    { targetWord: "RUHSAT", forbiddenWords: ["Belge", "Araba", "İzin", "Resmi", "Ehliyet"] },

    { targetWord: "SABUN", forbiddenWords: ["Temizlik", "Köpük", "Yıkamak", "El", "Banyo"] },
    { targetWord: "SAFİR", forbiddenWords: ["Taş", "Mavi", "Değerli", "Takı", "Mücevher"] },
    { targetWord: "SAKAL", forbiddenWords: ["Yüz", "Tıraş", "Erkek", "Kesmek", "Kıl"] },
    { targetWord: "SALÇA", forbiddenWords: ["Domates", "Yemek", "Kırmızı", "Sos", "Kavanoz"] },
    { targetWord: "SANTRAL", forbiddenWords: ["Telefon", "Bağlantı", "Elektrik", "Merkez", "Hat"] },
    { targetWord: "SARGI", forbiddenWords: ["Yara", "Bandaj", "Doktor", "Sarmak", "Pamuk"] },
    { targetWord: "SEFER", forbiddenWords: ["Yolculuk", "Otobüs", "Uçak", "Gidiş", "Plan"] },
    { targetWord: "SEPET", forbiddenWords: ["Piknik", "Market", "Taşımak", "Hasır", "Meyve"] },
    { targetWord: "SERAMİK", forbiddenWords: ["Toprak", "Fırın", "Sanat", "Tabak", "Kırılmak"] },
    { targetWord: "SERVİS", forbiddenWords: ["Yemek", "Garson", "Sunmak", "Tabak", "Restoran"] },

    { targetWord: "SESSİZ", forbiddenWords: ["Konuşmamak", "Gürültü", "Duyulmamak", "Huzur", "Fısıltı"] },
    { targetWord: "SİLAH", forbiddenWords: ["Ateş", "Mermi", "Tabanca", "Savaş", "Tehlike"] },
    { targetWord: "SİLGİ", forbiddenWords: ["Kalem", "Silmek", "Okul", "Hata", "Kağıt"] },
    { targetWord: "SİS", forbiddenWords: ["Hava", "Görüş", "Beyaz", "Bulut", "Soğuk"] },
    { targetWord: "SİTE", forbiddenWords: ["İnternet", "Web", "Sayfa", "Online", "Bağlantı"] },
    { targetWord: "SLOGAN", forbiddenWords: ["Kısa", "Söz", "Reklam", "Protesto", "Mesaj"] },
    { targetWord: "SPREY", forbiddenWords: ["Sıkmak", "Kutu", "Gaz", "Saç", "Boya"] },
    { targetWord: "STAJ", forbiddenWords: ["Öğrenci", "İş", "Deneyim", "Şirket", "Çalışmak"] },
    { targetWord: "STADYUM", forbiddenWords: ["Futbol", "Tribün", "Maç", "Saha", "Taraftar"] },
    { targetWord: "SUÇ", forbiddenWords: ["Ceza", "Mahkeme", "Polis", "Hapishane", "Yasa"] },

    { targetWord: "SÜPÜRGE", forbiddenWords: ["Temizlik", "Yer", "Toz", "Elektrikli", "Ev"] },
    { targetWord: "ŞARAP", forbiddenWords: ["İçecek", "Kırmızı", "Üzüm", "Şişe", "Alkol"] },
    { targetWord: "ŞERİT", forbiddenWords: ["Yol", "Çizgi", "Trafik", "Bant", "Bölmek"] },
    { targetWord: "ŞİFRE", forbiddenWords: ["Gizli", "Kod", "Parola", "Güvenlik", "Rakam"] },
    { targetWord: "ŞÖMİNE", forbiddenWords: ["Ateş", "Ev", "Odun", "Kış", "Isınmak"] },
    { targetWord: "TAÇ", forbiddenWords: ["Kral", "Kraliçe", "Altın", "Baş", "Mücevher"] },
    { targetWord: "TAHTA", forbiddenWords: ["Okul", "Yazmak", "Silmek", "Ahşap", "Sınıf"] },
    { targetWord: "TAKSİ", forbiddenWords: ["Şoför", "Araba", "Yolcu", "Ücret", "Sarı"] },
    { targetWord: "TANSİYON", forbiddenWords: ["Kan", "Basınç", "Doktor", "Ölçmek", "Sağlık"] },
    { targetWord: "TARTI", forbiddenWords: ["Kilo", "Ölçmek", "Ağırlık", "Market", "Gram"] },

    { targetWord: "TASLAK", forbiddenWords: ["Plan", "Çizim", "İlk", "Proje", "Deneme"] },
    { targetWord: "TAVLA", forbiddenWords: ["Zar", "Oyun", "Taş", "Masа", "Rakip"] },
    { targetWord: "TEBEŞİR", forbiddenWords: ["Tahta", "Yazmak", "Beyaz", "Okul", "Toz"] },
    { targetWord: "TECRÜBE", forbiddenWords: ["Deneyim", "Yaşamak", "Bilgi", "Uzman", "Yıllar"] },
    { targetWord: "TEKNE", forbiddenWords: ["Deniz", "Kürek", "Yelken", "Su", "Balık"] },
    { targetWord: "TEL", forbiddenWords: ["Metal", "İnce", "Elektrik", "Bağlamak", "Çit"] },
    { targetWord: "TERAZİ", forbiddenWords: ["Ölçmek", "Ağırlık", "Denge", "Kilo", "Market"] },
    { targetWord: "TERMİNAL", forbiddenWords: ["Otobüs", "Yolcu", "Bilet", "Peron", "Ulaşım"] },
    { targetWord: "TESTERE", forbiddenWords: ["Kesmek", "Tahta", "Ağaç", "Dişli", "Alet"] },
    { targetWord: "TİYATRO", forbiddenWords: ["Sahne", "Oyuncu", "Perde", "Gösteri", "Salon"] },

    { targetWord: "TOPAÇ", forbiddenWords: ["Döndürmek", "Oyuncak", "İp", "Çocuk", "Dönmek"] },
    { targetWord: "TRAFİK", forbiddenWords: ["Araba", "Yol", "Işık", "Polis", "Yoğun"] },
    { targetWord: "TRAMPET", forbiddenWords: ["Davul", "Ritim", "Müzik", "Baget", "Bando"] },
    { targetWord: "TULUM", forbiddenWords: ["Giysi", "Tek parça", "İş", "Kıyafet", "Mavi"] },
    { targetWord: "TURİST", forbiddenWords: ["Gezi", "Yabancı", "Şehir", "Rehber", "Tatil"] },
    { targetWord: "TÜNEL", forbiddenWords: ["Yeraltı", "Yol", "Geçmek", "Karanlık", "Dağ"] },
    { targetWord: "TÜP", forbiddenWords: ["Gaz", "Mutfak", "Yangın", "Silindir", "Yakmak"] },
    { targetWord: "UĞUR", forbiddenWords: ["Şans", "Talih", "Kısmet", "İnanmak", "Başarı"] },
    { targetWord: "ULUS", forbiddenWords: ["Millet", "Ülke", "Halk", "Devlet", "Toplum"] },
    { targetWord: "UMUT", forbiddenWords: ["Beklemek", "Gelecek", "İnanç", "Pozitif", "Hayal"] },




];

async function uploadData() {
    console.log("Yükleme işlemi başlıyor...");
    const collectionRef = db.collection('words');

    for (const word of words) {
        try {
            await collectionRef.add(word);
            console.log(`✅ Yüklendi: ${word.targetWord}`);
        } catch (error) {
            console.error(`❌ Hata (${word.targetWord}):`, error);
        }
    }
    console.log("🚀 Tüm kelimeler başarıyla Firebase'e gönderildi!");
}

uploadData();